In [3]:
pip install numpy



You should consider upgrading via the 'c:\users\chira\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [4]:
import numpy as np

In [5]:
a = np.array([[1,2,3],[4,5,6]])

In [6]:
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
print(a.shape)

(2, 3)


In [8]:
print(a.reshape)

<built-in method reshape of numpy.ndarray object at 0x00000265FE47B330>


In [9]:
print(a.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [10]:
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [11]:
x=np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [12]:
x=np.linspace(10,2)
print(x)

[10.          9.83673469  9.67346939  9.51020408  9.34693878  9.18367347
  9.02040816  8.85714286  8.69387755  8.53061224  8.36734694  8.20408163
  8.04081633  7.87755102  7.71428571  7.55102041  7.3877551   7.2244898
  7.06122449  6.89795918  6.73469388  6.57142857  6.40816327  6.24489796
  6.08163265  5.91836735  5.75510204  5.59183673  5.42857143  5.26530612
  5.10204082  4.93877551  4.7755102   4.6122449   4.44897959  4.28571429
  4.12244898  3.95918367  3.79591837  3.63265306  3.46938776  3.30612245
  3.14285714  2.97959184  2.81632653  2.65306122  2.48979592  2.32653061
  2.16326531  2.        ]


In [13]:
import json
with open(r'545483b2-9d22-4eae-b50a-bc3c888a3548.json','r') as file:
    data = json.load(file)
    

In [14]:
pprint(data)

Pretty printing has been turned OFF


In [15]:
data['analyzeResult']['pageResults']

[{'page': 1, 'tables': [{'rows': 5, 'columns': 6, 'cells': [{'rowIndex': 0, 'columnIndex': 0, 'text': 'FROM', 'isHeader': True, 'boundingBox': [0.36, 5.23, 0.6, 5.23, 0.6, 5.3, 0.36, 5.3]}, {'rowIndex': 0, 'columnIndex': 1, 'text': 'TO', 'isHeader': True, 'boundingBox': [0.835, 5.23, 1.06, 5.23, 1.06, 5.3, 0.835, 5.3]}, {'rowIndex': 0, 'columnIndex': 2, 'text': 'DUR(hr)', 'isHeader': True, 'boundingBox': [1.375, 5.23, 1.6, 5.23, 1.6, 5.315, 1.375, 5.315]}, {'rowIndex': 0, 'columnIndex': 3, 'text': 'CLASS', 'isHeader': True, 'boundingBox': [2.055, 5.23, 2.17, 5.23, 2.17, 5.3, 2.055, 5.3]}, {'rowIndex': 0, 'columnIndex': 4, 'text': 'RIG', 'isHeader': True, 'boundingBox': [2.53, 5.235, 2.765, 5.235, 2.765, 5.31, 2.53, 5.31]}, {'rowIndex': 0, 'columnIndex': 5, 'text': 'DESCRIPTION', 'isHeader': True, 'boundingBox': [2.95, 5.185, 7.45, 5.185, 7.45, 7.47, 2.95, 7.47]}, {'rowIndex': 1, 'columnIndex': 0, 'text': '00:00', 'boundingBox': [0.36, 5.23, 0.6, 5.23, 0.6, 5.3, 0.36, 5.3]}, {'rowIndex'

In [16]:
for i in data['analyzeResult']['pageResults']:
    for j in i['tables']:
        for k in j['cells']:
            print(k['text'])

FROM
TO
DUR(hr)
CLASS
RIG
DESCRIPTION
00:00
11:00
11,00
PT
MAIN
MW: Drilling with 8 1/2" BHA from 5721 m to 5742 m, with 15-30 klbf, 80-120 rpm, 25-33 klbf.ft, 600 gpm / 2550 psi. Notes: - EDS#4 (CSR+UBSR). - Keeping booster with 350 gpm / 550 psi, SBP 300 psi, Choke A 46-48%. - MPD in AP mode @ 5547 m with 9,80 ppg. - Using PWD internal gauge to estimate ECD and to calibrate MPD model. - Backreaming 20 m at 5723 m and 5731 m due to surface torque increasing. - Backreaming 5 m at 5737 m due to low ROP and backreaming 30 m at 5740 due to low ROP and BHA vibration. - Observing stall with 33 klbf.ft at 5739 m. - Observing MRIL tool failure at 5739 m.
11:00
12:30
1,50
NPT
MAIN
MW: Troubleshooting MRIL tool. Obs.: - Performing downlinks and manual mode switch, without sucess.
12:30
15:00
2,50
PT
MAIN
MW: Drilling with 8 1/2" BHA from 5742 m to 5747 m, with 15-37 klbf, 80 rpm, 25-32 klbf.ft, 600 gpm / 2550 psi. Notes: - Keeping booster with 350 gpm / 550 psi, SBP 300 psi, Choke A 46-48%. - M

In [17]:
data2 = []
cells = data['analyzeResult']['pageResults'][0]['tables'][0]['cells']
rowindex = [0,1,2,3,4]
for i in rowindex:
    lst = []
    for j in cells:
        if j['rowIndex'] == i:
            lst.append(j['text'])
    data2.append(lst)

In [18]:
print(data2)
len(data2)

[['FROM', 'TO', 'DUR(hr)', 'CLASS', 'RIG', 'DESCRIPTION'], ['00:00', '11:00', '11,00', 'PT', 'MAIN', 'MW: Drilling with 8 1/2" BHA from 5721 m to 5742 m, with 15-30 klbf, 80-120 rpm, 25-33 klbf.ft, 600 gpm / 2550 psi. Notes: - EDS#4 (CSR+UBSR). - Keeping booster with 350 gpm / 550 psi, SBP 300 psi, Choke A 46-48%. - MPD in AP mode @ 5547 m with 9,80 ppg. - Using PWD internal gauge to estimate ECD and to calibrate MPD model. - Backreaming 20 m at 5723 m and 5731 m due to surface torque increasing. - Backreaming 5 m at 5737 m due to low ROP and backreaming 30 m at 5740 due to low ROP and BHA vibration. - Observing stall with 33 klbf.ft at 5739 m. - Observing MRIL tool failure at 5739 m.'], ['11:00', '12:30', '1,50', 'NPT', 'MAIN', 'MW: Troubleshooting MRIL tool. Obs.: - Performing downlinks and manual mode switch, without sucess.'], ['12:30', '15:00', '2,50', 'PT', 'MAIN', 'MW: Drilling with 8 1/2" BHA from 5742 m to 5747 m, with 15-37 klbf, 80 rpm, 25-32 klbf.ft, 600 gpm / 2550 psi. Not

5

In [19]:
data3 = []
for i in cells:
    ind = int(i['rowIndex'])
    data3[ind].append(i['text'])

print(data3)

IndexError: list index out of range